language: java

before_install:
  - chmod +x mvnw

jdk:
  - openjdk8

services: 
  - docker

stages:
  - name: build

jobs:
  include:
    - name: Build image
      stage: build
      script:
        - mvn package
        - make build-image